### PR TITLE
Patch 3

### PR DESCRIPTION
**Pull request by seb3s**

### CODE REVIEW

**Comment by fhunleth** [comment]
@seb3s I'm not sure how to contact you except through here, so I hope you get this. I have merge permissions to mobius, but I'm not maintaining it. Merging your documentation update PRs is easy, though.

We ended not using Mobius at my company. A lot of us still find it interesting, but since we're not using it, it's hard to justify putting in more time. If you need to make more significant changes, could you please let me know if you'd like to maintain the project?

**Comment by seb3s** [comment]
Hi @fhunleth,
I do have integrated mobius in our project so I will have a interest into keeping the project running.
I'm curious : what option did you use instead of mobius ? Or it is just that you don't need a rrd tool anymore ?
I use it embedded within nerves :-)

**Comment by fhunleth** [comment]
@seb3s We ended up deciding that we were ok with having a little less information. That made it possible to send over our LTE links and record on our backend.

I'll give you write permission on the repository. Expect an invite shortly.

**Comment by fhunleth** [comment]
@seb3s I cancelled the repository invite and sent an organization invite in case you needed to do anything with the other repositories.

**Pull request merged**
